### ISSUE TITLE
Zero horizontal container padding for larger screens

### ISSUE THREAD

**Issue by midzer** [oklabflensburg/oddfl#1]
in https://github.com/oklabflensburg/oddfl/blob/27d7e8fcf9750a96442a0661ea7beedb4ee9c1cb/src/index.html#L96

for example and few other places.

IMO it looks better to have a small default horizontal padding, even on larger screens.

So, a possible fix would be to simply remove class `xl:px-0`.

**Comment by p3t3r67x0** [comment]
Hi @midzer thank your for your suggestion, I would love to ask @roaldchristesen to review your design improvement.
